# -*- coding: utf-8 -*-
"""ANN Day3 image with ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPHLlWO5TslPDBYJkzihR6eZGtzeKqbz

# Image Classification
image classification using ANN by Dr.tanapon Tantisripreecha 

Email: tanapon.tan@mahidol.ac.th

link: https://colab.research.google.com/drive/1kS55ZNVP_qHwxvidlzE5D-jCIHY-Y_Qs?usp=sharing

การสร้าง Classification โดยใช้ Machine learning กับรูปภาพ

# Import Libary
"""

import numpy as np
import io
import pandas as pd
import matplotlib as pl
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt      # MATLAB like plotting routines
import random                        # for generating random numbers

from keras.models import Sequential  # Model type to be used

from keras.layers.core import Dense, Dropout, Activation # Types of layers to be used in our model
from keras.utils import np_utils 

from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D, Flatten
#from keras.layers.normalization import BatchNormalization
from keras.layers.normalization import layer_normalization

"""# Loading dataset
การ Load image dataset เข้ามายัง colab จะสร้างข้อมูลใน Directory ดังต่อไปนี้

"/content/gdrive/My Drive/Colab Notebooks/dataset"
"""

from google.colab import drive #case mounted gdrive
drive.mount('/content/gdrive', force_remount=False)

import os  #case connect via OS
os.chdir("/content/gdrive/")
os.getcwd()

from google.colab import drive
drive.mount('/content/drive')

"""ดึงชื่อ image file และ category ของแต่ละไฟล์"""

path = "/content/drive/MyDrive/Colab Notebooks/img_dataset"
files = os.listdir(path)
categories = []

for filename in files:
    category = filename.split('.')[0]
    if 'fire' in category:
        categories.append("1")
    elif 'water' in category:
        categories.append("0")
    else: pass
df = pd.DataFrame({
    'filename': files,
    'category': categories
})

print(df.head(10))

"""แปลงไฟล์รูปภาพให้อยู่ในรูปแบบ numpay array แล้วเก็บไว้ในตัวแปร X และ category เก็บไว้ในตัวแปร y"""

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array

path = "/content/drive/MyDrive/Colab Notebooks/img_dataset"
files = os.listdir(path)

X =  np.empty([0])
y = np.empty([0])
for filename in files:
    print(path+"/"+filename)
    # load the image
    img = load_img(path+"/"+filename)

    #print(type(img))
    #print(img.format)
    #print(img.mode)
    print(img.size)
    img.show()


    # convert to numpy array
    img_array = img_to_array(img)   #จะถูก convert ให้เป็นแถวเป็นคอลลัมไม่ใช้ภาพแล้ว
   
    X = np.append (X,img_array)
    category = filename.split('.')[0]
    if 'fire' in category:
        y = np.append(y,[1])
    elif 'water' in category:
        y = np.append(y,[0])
    else: pass

y

X

X = X.reshape(len(y),120,120,3) #create 16 array list, new shape (120*120) , list ละ 3 แถว
x_vector = 120*120*3

X

"""https://www.pluralsight.com/guides/importing-image-data-into-numpy-arrays"""

print(X.shape) #สามตัวท้ายคือมีสามอาเรยมีสามกล่องอะ []
print(y.shape)
print(type(X))
print(type(y))

plt.rcParams['figure.figsize'] = (10,10) # change figure size to plot graph
c = ['water', 'fire']
for i in range(16):
    plt.subplot(4,4,i+1)
    img_array = X[i]
    plt.imshow(np.uint8(img_array))
    plt.title("Class {}".format(y[i]))
    
plt.tight_layout()

"""แบ่งข้อมูล train data และ test data"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1000)

print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", y_test.shape)

print(type(X_train))
print(type(y_train))

len_train  = len(X_train) #11
len_test = len(X_test) #5

X_train

plt.rcParams['figure.figsize'] = (9,9) # change figure size to plot graph

for i in range(11):
    plt.subplot(4,3,i+1)
    img_array = X_train[i]
    plt.imshow(np.uint8(img_array))
    plt.title("Class {}".format(y_train[i]))
    
plt.tight_layout()

plt.rcParams['figure.figsize'] = (9,9) # change figure size to plot graph

for i in range(5):
    plt.subplot(3,2,i+1)
    img_array = X_test[i]
    plt.imshow(np.uint8(img_array))
    plt.title("Class {}".format(y_test[i]))
    
plt.tight_layout()

X_train = X_train.reshape(len_train, x_vector) #ทำการ Fletten แต่ทำเอง x_vector 120*120*3
X_test = X_test.reshape(len_test, x_vector)   #ทำการ Fletten แต่ทำเอง x_vector 120*120*3

X_train = X_train.astype('float32')   # change integers to 32-bit floating point numbers
X_test = X_test.astype('float32')

X_train /= 255                    
X_test /= 255  # it is good practice to normalize the pixel values so that each pixel value has a value between 0 and 1

print("Training matrix shape", X_train.shape)
print("Testing matrix shape", X_test.shape)

X_train

nb_classes = 2 # number of unique digits

Y_train = np_utils.to_categorical(y_train, nb_classes) #Converts a class vector (integers) to binary class matrix.
Y_test = np_utils.to_categorical(y_test, nb_classes) #แปลงให้มันเป็นประเภท
print("y_train shape", y_train.shape)
print("y_test shape", y_test.shape)

"""Prepare the test and train Data

#Neural Network using Tensorflow
กำหนดจำนวน class ที่ต้องการใน Y_train และ Y_test (Y ตัวใหญ่)

Input layer
"""

#Neural Network using Tensorflow
model = Sequential()
model.add(Dense(10, input_shape=(x_vector,))) 
model.add(Activation('relu'))
#model.add(Dropout(0.2))

"""Hidden Layer"""

model.add(Dense(10))
model.add(Activation('relu'))
#model.add(Dropout(0.2))

"""Output Layer"""

model.add(Dense(2))
model.add(Activation('softmax'))
model.summary()

"""Complie model"""

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) #categorical_crossentropyใช้กับประเภท

"""Learning """

history = model.fit(X_train, Y_train, batch_size=5, epochs=10, validation_data=(X_test, Y_test))

"""Evaluation"""

score = model.evaluate(X_train, Y_train, verbose = 0)
print('Train loss : ', score[0])
print('Train accuracy : ', score[1])

score1 = model.evaluate(X_test, Y_test, verbose = 0)
print('Test loss : ', score1[0])
print('Test accuracy : ', score1[1])

import keras
print(keras.backend.backend()) 
import tensorflow as tf
print(tf.__version__)

tf.keras.Sequential([model,tf.keras.layers.Softmax()])
result = model.predict(X_test)
for i in range(5):
  print(np.argmax(result[i]))

plt.rcParams['figure.figsize'] = (9,9) # change figure size to plot graph

for i in range(5):
    plt.subplot(2,3,i+1)
    plt.imshow(X_test[i].reshape(120,120,3))
    plt.title("Class {}".format(y_test[i]))  
plt.tight_layout()

from keras.preprocessing.image import array_to_img
image_show = array_to_img(X_test[1].reshape(120,120,3))
image_show

print(np.argmax(result[1])) #water = 0 , fire = 1