# -*- coding: utf-8 -*-
"""NLTK_Movie_Pos_Neg

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYYyl7jDJoF8XuGJaDc6fnzdketIYacy
"""

import nltk
nltk.download('stopwords') 
nltk.download('wordnet')
nltk.download('movie_reviews')
nltk.download('punkt')

import pandas as pd
from nltk.corpus import movie_reviews, stopwords
reviews = []
for fileid in movie_reviews.fileids():
    tag, filename = fileid.split('/')
    reviews.append((tag, movie_reviews.raw(fileid)))
sample = pd.DataFrame(reviews, columns=['target', 'document'])
print(f'Dimensions: {sample.shape}')
sample.head()

sample.tail()

sample['target'].value_counts()

"""# ข้อ 1.
จงเขียนโปรแกรมเพื่อทำการตัดคำ ด้วย word_tokenize โดยสร้างเป็น column ใหม่ชื่อ word_token 
"""

from nltk.tokenize import word_tokenize      
tweetText = sample['document']
sample['word_token'] = tweetText.apply(word_tokenize)
sample

"""# ข้อ 2
จงเขียนโปรแกรมเพื่อทำ stemming จากคำที่ได้จากคำที่ได้จาก column word_token โดยสร้างเป็น column ใหม่ชื่อ stemmed 
"""

from nltk.stem import PorterStemmer 
def Stem(Name):
  ps = PorterStemmer()
  sent = Name
  ps_sent = [ps.stem(words_sent) for words_sent in sent]
  return  ps_sent
sample["stemmed"]  = sample['word_token'].apply(Stem)

sample

"""# ข้อ 3
จงเขียนโปรแกรมเพื่อตัด stopword จากคำที่ได้จาก column stemmed โดยสร้างเป็น column ใหม่ชื่อ stopword 
"""

from nltk.corpus import stopwords
def stop_word(text):
  stop_words = set(stopwords.words('english'))
  filtered_sentence = []
  for w in text:
    if w not in stop_words:
      filtered_sentence.append(w)
  return(filtered_sentence)
sample['stopword'] = sample['word_token'].apply(stop_word)
sample