# -*- coding: utf-8 -*-
"""Thanakorn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1staSgY0OnR7ctkbdbMHy_A2gZfhfbSjl
"""

pip install bs4

pip install requests

pip install songline

import bs4
import requests

data = requests.get('https://roms-download.com/roms/gameboy-advance/1-page')
soup = bs4.BeautifulSoup(data.text)
temp=soup.findAll('td')
name = temp[0].text.replace(' ','')
genre =temp[1].text.replace(' ','')
rating =temp[2].text.replace(' ','')
down = temp[3].text.replace(' ','')
size = temp[4].text.replace(' ','')
text = f'\nชื่อเกม : {name} ประเภทเกม : {genre} Rating : {rating} ยอดดาวน์โหลด : {down} ขนาดเกม : {size} '

import songline
token = 'tu3c1uhP1VQbLuqxJlfUsl3eAyfemK5zEXvqs4K7ZCp'
messenger = songline.Sendline(token)
messenger.sendtext(f'\nชื่อเกม : {name} ประเภทเกม : {genre} Rating : {rating} ยอดดาวน์โหลด : {down} ขนาดเกม : {size} ')
messenger.sendimage('https://roms-download.com/imgs/roms/gameboy-advance/p/pokemon-emerald-version-usa.jpg')

import songline
token = 'nAoODTQCcSwrsSb1d16RqeuKlXx2LvNJOEa4n05zsbi'
messenger = songline.Sendline(token)
messenger.sendtext(text)
messenger.sendimage('https://roms-download.com/imgs/roms/gameboy-advance/p/pokemon-emerald-version-usa.jpg')