# -*- coding: utf-8 -*-
"""store_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5yUT44nxx9CfjKtyAk4tjWgJ6c5NROa
"""

import pandas as pd
import numpy as np
import os

!pip install mlxtend

from google.colab import drive
drive.mount('/content/drive')

pach = '/content/drive/MyDrive/Colab Notebooks/dataset/store_data.csv'
data = pd.read_csv(pach,header=None)

data.head()

data.shape

data.values

data = data.apply(lambda x: ', '.join(x.dropna()),axis=1)
data = pd.DataFrame(data,columns=['products'])
data

data = list(data["products"].apply(lambda x : x.split(',')))

data

from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
data = pd.DataFrame(te_data,columns=te.columns_)
pd.set_option('display.max_columns', None)
data

from mlxtend.frequent_patterns import apriori
freq_items = apriori(data,min_support=0.01,use_colnames = True )
freq_items

freq_items['support'].max()

freq_items['support'].min()

from mlxtend.frequent_patterns import association_rules
df_res = association_rules(freq_items, metric = "confidence", min_threshold = 0.4)
df_res

conf_max = df_res['confidence'].max()
conf_max

conf_min = df_res['confidence'].min()
conf_min

df_filt = df_res[ (df_res["confidence"] == conf_min) | (df_res["confidence"] == conf_max) | (df_res["confidence"] == 0.5 )]
df_filt.sort_values("confidence",ascending = True)