# -*- coding: utf-8 -*-
"""MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRfQLe6n6DDrU3JrjqIkQEZN-qQZtfZH
"""

pip install dnspython

pip install pymongo

import datetime # Imports datetime library
import pymongo
from pymongo import MongoClient
client = MongoClient('mongodb+srv://thanakorn:26012544@cluster0.qoh2t.mongodb.net/Cluster0?retryWrites=true&w=majority')
db = client.test
# start client to connect to MongoDB server
client.stats

print(client.list_database_names())

db = client.get_database('student_db')
records = db.student_records

records.count_documents({ })

new_student = {
  'name': 'naphat',
  'roll_no': 321,
  'branch' : 'it'
}

records.insert_one(new_student)

new_students = [
{
  'name': 'anutin',
  'roll_no': 325,
  'branch' : 'buriram'
},{
  'name' : 'prayuth',
  'roll_no': 30,
  'branch' : 'bangkok'
}
]

records.insert(new_students)

list(records.find())

records.find_one({'roll_no' : 123})

student_updates = {
  'name' : 'prawit'
}

records.update_one({'roll_no': 123},{'$set': student_updates})

records.delete_one({'roll_no' : 123})