# -*- coding: utf-8 -*-
"""Thanakorn_MongoDB_Web.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWwhfozTKv5FM98DmzfZ9c8iXuRBdw0x
"""

pip install bs4

pip install requests

pip install dnspython

pip install pymongo

import datetime
import pymongo
from pymongo import MongoClient
client = MongoClient('mongodb+srv://thanakorn:26012544@cluster0.qoh2t.mongodb.net/Cluster0?retryWrites=true&w=majority')
db = client.test
# start client to connect to MongoDB server
client.stats

db = client.get_database('web_data')
records = db.data_game

records.count_documents({ })

import bs4
import requests

page = 1
name_list = []
genre_list = []
rating_list = []
down_list = []
size_list = []
while page <= 20:
  data = requests.get('https://roms-download.com/roms/gameboy-advance/'+str(page)+'-page')
  soup = bs4.BeautifulSoup(data.text)
  v = 0
  for c in soup.find_all('tr'):
    if v != 0:
      name_list.append(c.find('td',{'class':'mobile-14'}).find('a').text.replace('\n',''))
      genre_list.append(c.find('td',{'class':'hidden-xs'}).text.replace('\n',''))
      temp=c.findAll('td')
      rating_list.append(temp[2].text.replace('\n',''))
      temp=c.findAll('td')
      down_list.append(temp[3].text.replace('\n',''))
      temp=c.findAll('td')
      size_list.append(temp[4].text.replace('\n',''))
    v+=1
  print('Complete page number:',page)
  page+=1

for i in range(len(name_list)):
  new_game = {
    'name': name_list[i],
    'genre': genre_list[i],
    'rating' : rating_list[i],
    'download' : down_list[i],
    'size' : size_list[i]
  }
  records.insert_one(new_game)
  print('Complete insert data number: ', i+1)
print('*****Succeed*****')

list(records.find())