# -*- coding: utf-8 -*-
"""webscrap_temp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tFVFCOaVDyArNQ8ygLHi3JIjtSSaFbVJ

URL กับ urllib มีใน python อยุ่แล้ว
"""

pip install beautifulsoup4

pip install songline

from urllib.request import urlopen as req
from bs4 import BeautifulSoup as Soup

url = 'https://www.tmd.go.th/province.php?id=2'
webopen = req(url)
page_html = webopen.read()
print(page_html) #report in term of bytes
webopen.close()

#you must convert bytes to web_page using beutifulsoup
data = Soup(page_html,'html.parser')
print(data)

temp = data.findAll('td',{'class':'strokeme'})
print(temp)

#ตัดคำให้เหลือแค่องศา โดยใช้.text เพื่อเอาแค่ข้อความองศาเอา tag ออก
result = temp[0].text #temp ตัวที่ 0 คือตัวข้อความแรกใน tag
print(result)

#ดึงค่าจังหวัดมาด้วย
province = data.findAll('span',{'class':'title'}) # ('tag', {'class':'ชื่อคลาส'})
pv = province[0].text.replace(' ','') #ลบช่องว่างหน้าด้านเชียงใหม่ ที่ไม่ใช่ space แต่ให้copy ช่องว่างด้านหน้าเชียงใหม่มาวาง
print(pv)

#จัด format ของผลลัพธ์
print('จังหวัด : {} อุณหภูมิ: {}'.format(pv,result)) #จัด format
print(f'จังหวัด :{pv} อุณหภูมิ: {result}') # F ย่อมาจาก Format

#create function
def Temperature(pvid):
  url = 'https://www.tmd.go.th/province.php?id='+str(pvid)
  #pvid = provice id from website
  webopen = req(url)
  page_html = webopen.read()
  webopen.close()
  data = Soup(page_html,'html.parser')
  temp = data.findAll('td',{'class':'strokeme'})
  result = temp[0].text
  province = data.findAll('span',{'class':'title'})
  pv = province[0].text.replace(' ','') #ลบช่องว่างหน้าด้านเชียงใหม่ ที่ไม่ใช่ space แต่ให้copy ช่องว่าด้านหน้าเชี้ยงใหม่มาวาง
  #print('จังหวัด : {} อุณหภูมิ: {}'.format(pv,result)) #จัด format
  print(f'จังหวัด :{pv} อุณหภูมิ: {result}') #จัด format แบบ python v. 3
  text = 'จังหวัด : {} อุณหภูมิ: {}'.format(pv,result)
  return text
  
for i in range(1,10):
  Temperature(i)

#ดักจับ error กรณีที่ไม่มีfield ที่ระบุไว้หรือจังหวัดไม่มีข้อมูล
for i in range(1,100):
  try:
    Temperature(i)
  except Exception as e:
    print('the data is empty.',e)

import songline
token = 'jasy4eAUkEOzXhctQ4sNn5iQ0mmqJo5Z23NJ2Gp6FzY' #don’t public and u get from website bot.line.me/my
messenger = songline.Sendline(token)
messenger.sendtext('Hello')

messenger.sticker(607,10)

messenger.sendimage('https://www.siamarcheep.com/wp-content/uploads/siamarcheep-28-09-2017-2.jpg')

import songline
token = 'jasy4eAUkEOzXhctQ4sNn5iQ0mmqJo5Z23NJ2Gp6FzY' #myjina u must keep this no public u get from website bot.line.me/my
messenger = songline.Sendline(token)
myprovince = Temperature(43)
messenger.sendtext(myprovince)